### DISCUSSION TITLE
features: Change Biome in the nether and end worlds

### DISCUSSION THREAD

**Discussion by Zarkness2** [BG-Software-LLC/SuperiorSkyblock2#1212] [Implemented Feature Requests] [answered]
feature: add the possibility of changing the biomes in the nether and end worlds. @OmerBenGera 

in terms of configuration would be to add the following to choose the world in which to change the biome

```yml
  '&':
    biome: BASALT_DELTAS
    environment: Nether # Spigot WORLD ENVIRONMENT TYPE. World environment value. Default Normal.
    access:
      type: PLAYER_HEAD
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU2Y2E1YzY3OTMzNmRkNGYzMjYyZjRmYmMyM2MxYTJlZTBkODJhN2ZkODFlNmU2MjMzN2U1ZmQ1YzcifX19'
      name: '&eNether Wastes Biome &a(Available)'
      lore:
        - '&7Change your island biome to the nether.'
        - '&cWarning ice, snow and water must go!'
    no-access:
      type: PLAYER_HEAD
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU2Y2E1YzY3OTMzNmRkNGYzMjYyZjRmYmMyM2MxYTJlZTBkODJhN2ZkODFlNmU2MjMzN2U1ZmQ1YzcifX19'
      name: '&eNether Wastes Biome &c(Unavailable)'
      lore:
        - '&7Change your island biome to the nether.'
        - '&cWarning ice snow, and water must go!'
```
