### DISCUSSION TITLE
Auto rewards system to specific top islands in specific cooldown

### DISCUSSION THREAD

**Discussion by OmerBenGera** [BG-Software-LLC/SuperiorSkyblock2#183] [Pending Feature Requests]
Auto rewards system to specific top islands in specific cooldown

**Comment by Tptuaazn** [comment]
and delete upgrades, islands, .. when it ends?

**Reply by OmerBenGera** [reply]
> and delete upgrades, islands, .. when it ends?

I am sorry?

**Comment by ItchyDitchy** [comment]
So this is what I thought of...

\> **Commands:**
**/is admin resetRewards [reward-id]** - _Resets the timer_

\> **Configuration:**
```yml
...
...
# All settings for timely rewards
autorewards:

  # Rewards given to top islands based on the sorting.
  rewards:

    # ID for the reward
    top1worth:
      
      # Postion of island depending on order.
      position: 1

      # Set a cooldown for upgrading island values.
      # Cooldowns are in seconds.
      # You can disable this feature by setting it to -1
      cooldown: 86400

     # How should the island top be ordered?
     # Use WORTH, LEVEL, RATING or PLAYERS.
      order: 'WORTH'

      # Commands that will be executed by console.
      commands:
        - 'island admin msgall %player% &f'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your island received the top 1 worth daily reward!'
        - 'broadcast The daily island worth has been given!'

    top1level:
      position: 1
      cooldown: 86400
      order: 'LEVEL'
      commands:
        - 'island admin msgall %player% &f'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your island received the top 1 level daily reward!'

    top2level:
      position: 2
      cooldown: 86400
      order: 'LEVEL'
      commands:
        - 'island admin msgall %player% &f'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your island received the top 2 level daily reward!'
...
...
```

\> **Code:**
Reward class
Timers (probably runnables)
RewardsHandler

\> **API:**
CreateReward, StartRewardTimer, SetRewardTimer, StopRewardTimer, SetCommands, GetRewardTimer, GetCommands, GetPosition, SetPostion, SetOrder, ETC

I guess this is my idea for this feature...
I already made this as an addon but it probably needs some tweaking as I am just a beginner.
