### DISCUSSION TITLE
allow customModel to missions

### DISCUSSION THREAD

**Discussion by AlmostPanda** [BG-Software-LLC/SuperiorSkyblock2#2183] [Pending Feature Requests]
Hi, I've got a great idea to add `customModel` for required-items in mission.

It occurred to me that servers could use the ability to create items with a CustomModel value. Which is not a bad idea at all in my opinion, some plugins have the option to set a custommodel value on items, like Oraxen or ItemsAdder, but why wouldn't this option work for items without these plugins?

Its so simple to get customModel on any item without these plugins, just simple /give item{CustomModelData:<id>}

the example of required-item for mission can look like that
```
required-items:
  '1':
    types:
      - 'BOOK'
    customModel: 2201
    amount: 1
```
Edit: a fix in text
