### DISCUSSION TITLE
More placeholders in missions module

### DISCUSSION THREAD

**Discussion by RUYSUE** [BG-Software-LLC/SuperiorSkyblock2#2349] [Pending Feature Requests]
Now there're some overall placeholder ({0}, {1} and {2}) and exact placeholders like '{value_zombie}'. Lacking placeholders for specific 'overall' collection.

For example, in slayer mission, I would set a mission like this:

```
required-entities:
  '1':
    types:
      - 'SKELETON'
      - 'STRAY'
    amount: 32
  '2':
    types:
      - 'ZOMBIE'
      - 'HUSK'
    amount: 32
```

With existing placeholders, I cant record 'SKELETON and STRAY' with 'ZOMBIE and HUSK' separately, but only spliting these into four items, and count them independently. And this may comfuse players on how long they are away from completing this mission.

```
icons:
  not-completed:
    type: PAPER
    name: '&aSLAYER'
    lore:
      - '&6SEKELETON KILLED: &7{value_skeleton}'
      - '&6STRAY KILLED: &7{value_stray}'
      - '&6ZOMBIE KILLED: &7{value_zombie}'
      - '&6HUSK KILLED: &7{value_husk}'
```

Therefore, I suggest adding placeholders such as '{value_1}' and '{value_2}' to classify and statistically analyze task conditions. (In this example '{value_1}' stands for SKELETON and STRAY killed, '{value_2}' stands for ZOMBIE and HUSK killed)

**Comment by OmerBenGera** [comment]
This was a bug and it is fixed in latest dev builds.
The placeholders `{value_skeleton}` and `{value_stray}` will give the same result - the progress for that task.

**Reply by RUYSUE** [reply]
Ok, I will try this.

By the way, what if I set completely different mobs in one group? Like this:

```
required-entities:
  '1':
    types:
      - 'SKELETON'
      - 'ZOMBIE'
    amount: 40
  '2':
    types:
      - 'WITHER_SKELETON'
      - 'BLAZE'
    amount: 20
```

I wonder if there're placeholders can be used in this situation, thanks for your answering.
