### DISCUSSION TITLE
Menus are unupdatable

### DISCUSSION THREAD

**Discussion by hamza-cskn** [BG-Software-LLC/SuperiorSkyblock2#327] [Pending Feature Requests]
```yaml
commands:
   'O':
      - '[player] autopickup'
      - '[back]'
      - '[player] is panel'
```
/autopickup command is a toggle command. i wanna when i click the 'O' icon, update the control-panel menu. but commands that is above, working **partially**.

also this is buggy:
```yaml
commands:
   'O':
      - '[player] autopickup'
      - '[player] is panel'
```

**i just wanna '[update]' section like '[back]'.**
