### ISSUE TITLE
Placeholders not parsing on console

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1090]
### Minecraft's Version

1.16.5, paperspigot

### Plugin's Version

1.9.0.588

### Describe the bug

I can't parse placeholders via MyCommand (even tho any other placeholders work apart from SuperiorSkyblock2)

> tops
[00:04:13 INFO]: kalasnyikovxx, wtfbnc, Kriptoniasz
[00:04:13 INFO]: [Mycmd] An error occurred on console variable replace.
[00:04:13 INFO]: %superior_island_top_level_leader_1%, %superior_island_top_level_leader_2%, %superior_island_top_level_leader_3%

but in game, if you run /tops it runs without issues, the issue is only with console.

### To Reproduce

```
'top3':
  command: /tops
  type: TEXT
  text:
  - '%ajlb_lb_ezblocks_blocks_1_alltime_name%, %ajlb_lb_ezblocks_blocks_2_alltime_name%, %ajlb_lb_ezblocks_blocks_3_alltime_name%'
  - '%superior_island_top_level_leader_1%, %superior_island_top_level_leader_2%, %superior_island_top_level_leader_3%'
  permission-required: true
  register: true
```
