### ISSUE TITLE
Upgrade not working via permission

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1332]
### Minecraft's Version

1.18.2

### Plugin's Version

775

### Describe the bug

My players can't upgrade an upgrade that has permission (even tho they have the permission)

### To Reproduce

```
  crop-growth:
    '1':
      price: 25000.0
      price-type: 'placeholders'
      placeholder: '%RevEnchants_Currency_Korona%'
      withdraw-commands:
      - 're Currency remove Korona %player% 25000'
      crop-growth: 1
      commands:
      - is admin setupgrade %player% crop-growth 2
      - is admin msgall %player% &e&lSkyBlock &8» &fA növények növekedési sebessége gyorsítva lett!
      permission: 'skyblock.upgrade.crop2'
```
