### ISSUE TITLE
Member of an island can not leave

### ISSUE THREAD

**Issue by nhanledev** [BG-Software-LLC/SuperiorSkyblock2#1344]
### Minecraft's Version

paper-1.19.2-138.jar

### Plugin's Version

SuperiorSkyblock2-1.11.1-b778.jar

### Describe the bug

When a member want to leave the island (quit being an member of that island), the command `/is leave` does not allow him to do that. It shows `LEAVE_ISLAND_AS_LEADER` error instead.

Checked the role via `/is admin show PlayerName` and it shows that player is a Member, not Leader.

I think there should be something in this line https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/84c5c4b29f2b8236c66c9e70ad0c46d8093561cb/src/main/java/com/bgsoftware/superiorskyblock/commands/player/CmdLeave.java#L64

### To Reproduce

- Create a new island
- Invite a player
- Player accept invitation
- Type `/is leave`
- Player can not leave

### Additional Information

My config only change the ladder:

```
island-roles:
  # This role is given to players that are not part of your island.
  guest:
    # A custom name for the role.
    name: Visitor
    # A list of default permissions for guests.
    permissions: []

  # This role is given to players that are co-op.
  coop:
    name: Trusted
    permissions:
    - ANIMAL_BREED
    - ANIMAL_DAMAGE
    - BREAK
    - BUILD
    - CLOSE_BYPASS
    - CROPS_GROWTH
    - DROP_ITEMS
    - ENDER_PEARL
    - EXPEL_BYPASS
    - FARM_TRAMPING
    - FERTILIZE
    - FISH
    - HORSE_INTERACT
    - INTERACT
    - ITEM_FRAME
    - LEASH
    - MINECART_DAMAGE
    - MINECART_ENTER
    - MINECART_OPEN
    - MINECART_PLACE
    - MONSTER_DAMAGE
    - NAME_ENTITY
    - PAINTING
    - PICKUP_DROPS
    - PICKUP_FISH
    - SIGN_INTERACT
    - TURTLE_EGG_TRAMPING
    - USE
    - VILLAGER_TRADING

  # The roles ladder for island members.
  # All the island member roles go here.
  #  - You can add as many roles as you'd like.
  #  - The default role for new members has a weight of 0.
  #  - Every role has all the permissions of the role before it.
  #  - Every role should have a custom id, to determine the role if the name is changed.
  #    Do not change ids!!! They don't have to be in an order.
  ladder:
    member:
      id: 0
      name: Member
      weight: 0
      permissions:
      - ANIMAL_SPAWN
      - CHEST_ACCESS
      - DEPOSIT_MONEY
      - ISLAND_CHEST
      - MONSTER_SPAWN
      - RANKUP
      - SPAWNER_BREAK
        # - FLY
    # mod:
    #   id: 1
    #   name: Moderator
    #   weight: 1
    #   permissions: []
        # - BAN_MEMBER
        # - CLOSE_ISLAND
        # - DELETE_WARP
        # - EXPEL_PLAYERS
        # - INVITE_MEMBER
        # - KICK_MEMBER
        # - OPEN_ISLAND
        # - RATINGS_SHOW
        # - SET_WARP
        # - VALUABLE_BREAK
        # - WITHDRAW_MONEY
    # admin:
    #   id: 2
    #   name: Admin
    #   weight: 2
    #   permissions: []
        # - COOP_MEMBER
        # - DEMOTE_MEMBERS
        # - DISCORD_SHOW
        # - PAYPAL_SHOW
        # - PROMOTE_MEMBERS
        # - SET_BIOME
        # - SET_DISCORD
        # - SET_HOME
        # - SET_PAYPAL
        # - SET_PERMISSION
        # - SET_ROLE
        # - SET_SETTINGS
        # - UNCOOP_MEMBER
    leader:
      id: 3
      name: Owner
      weight: 3
      permissions:
      - ALL
 ```
