### ISSUE TITLE
Minions from JetsMinions support

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1499]
### Minecraft's Version

paper 1.12.2

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b915

### Describe the bug

Sometimes the cob gen doesn't wanna work with JetsMinions
I contacted the discord server and they replied me this:
![image](https://user-images.githubusercontent.com/41546701/206775489-212aed7b-7be9-4567-8104-7abc51ca4b9c.png)

When the player mines the cob gen it works without issues.

### To Reproduce

![image](https://user-images.githubusercontent.com/41546701/206775891-55fe96be-7b73-4c99-a089-01c63230321f.png)

**Comment by OmerBenGera** [comment]
I am in a talk with Jet about it already, thanks for opening an issue
He reached me a few days ago with this issue.
Hopefully we will be able to sort it out as soon as possible

**Comment by OmerBenGera** [comment]
I can't seem to replicate it myself
Are you able to replicate it with only SSB and JetsMinions installed?

**Comment by Superalex0102** [comment]
Yes, but it is quite rare

**Comment by DuneSciFye** [comment]
I've had a severe case of this issue for many weeks now. If you want, you can come on my server and I'll show you

**Comment by OmerBenGera** [comment]
> I've had a severe case of this issue for many weeks now. If you want, you can come on my server and I'll show you

Try replicating it on a server with only JetsMinions and SSB as well

**Comment by Superalex0102** [comment]
I don't know if it is regarded or not, but FAWE is spawmming this message every 30 seconds or so:
`[23:15:19 INFO]: (FAWE) [FAWE `tick-limiter`] Detected and cancelled physics lag source at Location{world=CraftWorld{name=SkyBlock},x=2733.0,y=237.0,z=-1797.0,pitch=0.0,yaw=0.0}`
I teleported to the location and it is a cob gen.

**Comment by DuneSciFye** [comment]
Oh shoot your right. I also get those messages.

**Comment by DuneSciFye** [comment]
Let me test without fawe

**Comment by Superalex0102** [comment]
> Let me test without fawe

I turned off tick-limiter and it is working fine for now

**Comment by Superalex0102** [comment]
```
# Generic tick limiter (not necessarily WorldEdit related, but useful to stop abuse)
tick-limiter:
  # Enable the limiter
  enabled: false
  # The interval in ticks
  interval: 20
  # Max falling blocks per interval (per chunk)
  falling: 64
  # Max physics per interval (excluding redstone)
  physics-ms: 10
  # Max item spawns per interval (per chunk)
  items: 256
  # Whether fireworks can load chunks
  #  - Fireworks usually travel vertically so do not load any chunks
  #  - Horizontal fireworks can be hacked in to crash a server
  fireworks-load-chunks: false
```
