### ISSUE TITLE
Does not generate end and nether islands with myworlds plugin

### ISSUE THREAD

**Issue by Zarkness** [BG-Software-LLC/SuperiorSkyblock2#1636]
### Minecraft's Version

Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### Plugin's Version

SuperiorSkyblock2-version 2022.9-b977

### Describe the bug

using the myworlds plugin and going to the nether or the end through the portals does not generate the islands but an empty world and in the end world as seen in the second picture the bossbar that spawned the enderdragon appears

![image](https://user-images.githubusercontent.com/48263644/225307865-90c79897-f607-44b8-a29a-97b0748bd342.png)
![image](https://user-images.githubusercontent.com/48263644/225308073-df2e8991-66ad-4374-bde6-33787de92ac6.png)

### To Reproduce

to reproduce the error or as it happens to me is having the default configuration of myworlds and superiorskyblock2 the only thing I touched in the SSB was to activate the enabled option in both nether and end, then I create my island, I get the obsidian and a flint and steel and turn on the portal of the nether and when I enter the previous photos comes out

**Comment by OmerBenGera** [comment]
Hey, open your My_Worlds configuration file, and search for this section:
```
# Turns different types of portals on or off
# When the portal is disabled, MyWorlds will not handle the portal's logic
enabledPortals:
  # Turns handling of nether portal teleportation on or off
  # Vanilla Minecraft will handle nether portals when disabled
  netherPortal: false
  # Turns handling of end portal teleportation on or off
  # Vanilla Minecraft will handle end portals when disabled
  endPortal: false
  # Enables or disables the water stream portals
  waterPortal: false
```
Make sure you disable all the portals here.
When you have My_Worlds handling the portals for you, SSB can't handle them and therefore it breaks the portals.
