### ISSUE TITLE
Command cooldown on /is recalc does not work

### ISSUE THREAD

**Issue by L0tfy** [BG-Software-LLC/SuperiorSkyblock2#1652]
### Minecraft's Version

1.16.5
paperspigot tested
purpur tested

### Plugin's Version

 2023.1

### Describe the bug

I want island levels not to update automatically. I just want it updated by typing "/is level". Also, the duration of the "/is level" command doesn't work.

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Island level and worth are updated automatically as `/is recalc` is a really heavy task performance-wise.

About the cooldown bug, upload your config file to pastebin and send a link to it here.

**Comment by L0tfy** [comment]
> Island level and worth are updated automatically as `/is recalc` is a really heavy task performance-wise.
> 
> About the cooldown bug, upload your config file to pastebin and send a link to it here.

https://binshare.net/6s2i3hKggoI1uQG2yTK0

**Comment by exzolink** [comment]
60 means 60 milliseconds

**Comment by OmerBenGera** [comment]
As @exzolink said, the cooldown is in milliseconds, not seconds. This is also stated in the default config:
```
# A list of commands that should have cooldown.
# Cooldowns are in milliseconds.
# You can disable this section by using:
# commands-cooldown:
#   random:
#     cooldown: 0
commands-cooldown:
  recalc:
    cooldown: 30000
    bypass-permission: superior.cooldown.bypass.recalc
```

Make sure you configure it correctly.
