### ISSUE TITLE
Boats limit do not work in entity-limits

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1710]
### Minecraft's Version

Core: PurPur 1.19.3

### Plugin's Version

PL. ver: 2023.1

### Describe the bug

I'm just trying to limit the number of boats that can exist on the island, but it doesn't seem to be possible, although minecarts work. I am using entity-limits and plugins/SuperiorSkyblock2/modules/upgrades/config.yml file for this. 

See the video: https://youtu.be/E6lBp2cJfiM

What I have tried (None of this helped):

```
  boats-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      entity-limits:
        BOAT: 2
      commands:
```
  
```
boats-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      entity-limits:
        CHEST_BOAT: 2
      commands:
```
      
```
boats-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      entity-limits:
        CHEST_BOAT: 2
        BOAT: 2
      commands:
```
 
```
  boats-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      entity-limits:
        OAK_CHEST_BOAT: 2
        OAK_BOAT: 2
        SPRUCE_BOAT: 2
        SPRUCE_CHET_BOAT: 2
        BIRCH_BOAT: 2
        BIRCH_CHEST_BOAT: 2
        JUNGLE_BOAT: 2
        JUNGLE_CHEST_BOAT: 2
        ACACIA_BOAT: 2
        ACACIA_CHEST_BOAT: 2
        DARK_OAK_BOAT: 2
        DARK_OAK_CHEST_BOAT: 2
        MANGROVE_BOAT: 2
        MANGROVE_OAK_CHEST_BOAT: 2
      commands:
```
 
```
  boats-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      entity-limits:
        OAK_CHEST_BOAT: 2
        OAK_BOAT: 2
        SPRUCE_BOAT: 2
        SPRUCE_CHET_BOAT: 2
        BIRCH_BOAT: 2
        BIRCH_CHEST_BOAT: 2
        JUNGLE_BOAT: 2
        JUNGLE_CHEST_BOAT: 2
        ACACIA_BOAT: 2
        ACACIA_CHEST_BOAT: 2
        DARK_OAK_BOAT: 2
        DARK_OAK_CHEST_BOAT: 2
        MANGROVE_BOAT: 2
        MANGROVE_OAK_CHEST_BOAT: 2
        CHEST_BOAT: 2
        BOAT: 2
      commands:
```

### To Reproduce

To reproduce dd to plugins/SuperiorSkyblock2/modules/upgrades/config.yml :

```
  boats-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      entity-limits:
        OAK_CHEST_BOAT: 2
        OAK_BOAT: 2
        SPRUCE_BOAT: 2
        SPRUCE_CHET_BOAT: 2
        BIRCH_BOAT: 2
        BIRCH_CHEST_BOAT: 2
        JUNGLE_BOAT: 2
        JUNGLE_CHEST_BOAT: 2
        ACACIA_BOAT: 2
        ACACIA_CHEST_BOAT: 2
        DARK_OAK_BOAT: 2
        DARK_OAK_CHEST_BOAT: 2
        MANGROVE_BOAT: 2
        MANGROVE_OAK_CHEST_BOAT: 2
        CHEST_BOAT: 2
        BOAT: 2
      commands:
```
      
restart your server
    
create island

spawn boats

(boats are unlimited)
