### ISSUE TITLE
Ender Dragon doesn't spawn 1.20.1

### ISSUE THREAD

**Issue by natr566** [BG-Software-LLC/SuperiorSkyblock2#1759]
### Minecraft's Version

Paper version git-Paper-49 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e8bec64)

### Plugin's Version

SuperiorSkyblock2 version 2023.2

### Describe the bug

When going to end the dragon does not spawn. Tried the default island with a clean install and still doesn't work.
```
  end:
    # Should the end world be enabled?
    enabled: true
    # Should the end be unlocked by default to islands?
    unlock: true
    # Custom name for the end world.
    # When empty, the name will be "<island-world>_the_end"
    name: ''
    # Should the schematics in this world will not be counted towards worth and level values?
    schematic-offset: true
    # The default biome for the world.
    # If the biome is invalid, THE_END will be used.
    biome: THE_END
    # Settings related to dragon fights on the server.
    dragon-fight:
      # Whether dragon fights should be enabled.
      # If enabled, each island will have it's own ender dragon to battle with.
      enabled: true
      # The offset of the end portal (where it should be spawning) from the middle of the island.
      # The format is '<offset-x>, <offset-y>, <offset-z>' (may be negative).
      # Having the offset going beyond the island-radius is an undefined behavior!
      portal-offset: '0,0,0'
```

### To Reproduce

Create new server got to end.
