### ISSUE TITLE
Missions: Wrong example in the documentation

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1777]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

I noticed that there is an error in the documentation. I tried to make a mission that would calculate the growth of a carrot shortbread, but it did not work. The mission simply did not count anything. Placeholders {value_carrots} and {value_potatoes} always called 0. 

What I tried, according to the documentation (**this doesnt work for me!**):

```
required-plants:
  '1':
    types:
      - 'CARROTS'
    amount: 800
  '2':
    types:
      - 'POTATOES'
    amount: 800
```
 
And placeholders `{value_potatoes}`, `{value_carrots}`

Docs: https://wiki.bg-software.com/superiorskyblock/overview/missions/farmingmissions
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/150d0308-bf5e-43bc-8af0-2ca1967888fa)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/0950eb31-3dd7-49e6-85e4-97eba959dfb4)

What does actually work fro me:

 ```
required-plants:
  '1':
    types:
      - 'CARROT'
    amount: 800
  '2':
    types:
      - 'POTATO'
    amount: 800
```

And placeholders `{value_potatoe}`, `{value_carrot}`
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/bfb333c9-fecc-4645-97f4-b2b767c8fbea)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/d1295388-f02d-4952-a9c4-d63af8356f5a)

Please, fix text in the documentation

### To Reproduce

Try use `CARROTS `instead of `CARROT` and `{value_carrots}` instead of `{value_carrot}` => with `S` it doesn;t work
Same with `POTATO` and other plants.

### Additional Information

my mission in the `.txt` doemat:
[farming2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11967831/farming2.txt) (works)
