### ISSUE TITLE
Chorus doesnt work at FarmingMissions

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1781]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

I've tried many different variations, but Farming Missions doesn't seem to notice the growth of choruses.
What I tried:
```
required-plants:
  '1':
    types:
      - 'CHORUS'
    amount: 100
```

```
required-plants:
  '1':
    types:
      - 'CHORUS_PLANT'
    amount: 100
   
```
 
```
required-plants:
  '1':
    types:
      - 'CHORUS_FLOWER'
    amount: 100
```

None of this helped.

### To Reproduce

Try to set the mission with CHORUS as required-plants (doesnt work)
