### ISSUE TITLE
EnchantingMissions: a several same items don't work

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1784]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b45

### Describe the bug

I'm trying to create a mission where, for example, you need to enchant 3 iron sets of armor (for example, each piece of armor for defense 4 durability 3)

```
required-enchants:
  '1':
    types:
      - 'IRON_HELMET'
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 3
      WATER_WORKER: 1
    **amount: 3**
```

But 1st:
 As I already noticed (https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1783) placeholders don't support quantity, they only say YES or NO.
 
 2nd:
 Despite the fact that amount: 3, placeholder changes to YES immediately after the first enchantment. One gets the impression that enchantments do not support the amount, but this is strange.

### To Reproduce

Create mission of EnchantingMissions jar
set:
```
required-enchants:
  '1':
    types:
      - 'IRON_HELMET'
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 3
      WATER_WORKER: 1
    amount: 3
```
go to the server and try to enchant it.
 you will complete the mission after 1st helmet.

### Additional Information

my mission in .txt format:
[enchanting2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11986526/enchanting2.txt)
