### ISSUE TITLE
Roles for cooperators - a bug?

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1797]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b45

### Describe the bug

Coops in `/is coops` menu have Roles. What is it? Isn't `coop` a role in itself?  Then what rights will apply to her? Is it possible to disable additional rights for cooperators? I expect that the cooperators will only have the rights that I specify in the configuration file:
```
  # This role is given to players that are co-op.
  coop:
    name: coop
    permissions:
    - ANIMAL_BREED
    - ANIMAL_DAMAGE
    - ANIMAL_SHEAR
    - ...
```
`/is coops` menu config:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/f800dceb-9ff4-4374-8c64-2c513198f0df)

minecraft `/is coops` menu:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/39f22ba8-b2e0-466d-8a5d-fc8cefeaecdc)

### To Reproduce

Give coop to a player
Type /is coops
See "Role" in the lore
