### ISSUE TITLE
Welcome and Warp sign bad color handling

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1916]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15414 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9107801 on HEAD)
Unknown version
Previous version: git-SlimeWorldManager-15378 (MC: 1.20.2)

### Plugin's Version

SuperiorSkyblock2: 2023.3-b100
Luckperms: 5.4.104
CMI: 9.6.7.5

### Describe the bug

When player who doesnt have permission for sign color formatting creates [Warp] or [Welcome] sing, the text doesnt change color. Text will be exactly '&a[Welcome]'

Config:
```yml
# All settings related to the visitors sign.
visitors-sign:
  # Whether a visitors sign is required for others to visit islands.
  # If set to false, visitors will be teleported to the regular island home when using `/is visit`
  required-for-visit: true
  # Set the line to create the visitors sign.
  line: '[Welcome]'
  # The line that will be displayed when the sign is active.
  active: '&a[Welcome]'
  # The line that will be displayed when the sign is inactive.
  inactive: '&c[Welcome]'
  ```

### To Reproduce

Create island and place sign with [Welcome] text on the 1st line as player without `cmi.colors.signs.*` permission node

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79375965/61f830a0-2d1d-4112-b94e-67559e46a9fb)
