### ISSUE TITLE
Can't lock schematics for an island behind a permission

### ISSUE THREAD

**Issue by findbottest** [BG-Software-LLC/SuperiorSkyblock2#1944]
### Minecraft's Version

1.20.1 paper.

### Plugin's Version

2023.2

### Describe the bug

i can not lock island schematics in the island-create menu.
i have tried 

  '-':
    schematic: 'Windmill'
    **required-permission: 'skyblock.islands.ranks'**
    biome: PLAINS
    
      '-':
    schematic: 'Windmill'
    **permission: 'skyblock.islands.ranks'**
    biome: PLAINS

but the islands remained unlocked, the wiki says to use permission: but no luck either.. is this a bug? thanks.

### To Reproduce

in island-creation.yml, use permission: 'skyblock.islands.ranks' as the island schematic unlock.

**Comment by OmerBenGera** [comment]
https://wiki.bg-software.com/superiorskyblock/overview/menus#permissions-section

Let me know if it works.

**Comment by findbottest** [comment]
> https://wiki.bg-software.com/superiorskyblock/overview/menus#permissions-section
> 
> Let me know if it works.

The wiki linked says to use permission: which is exactly what i have already done above.

**Comment by Davisiiiik** [comment]
@findbottest I think you are using the menu incorrectly, in that case, I will show you my working example of VIP island:

```yml
items:
  'V':
    schematic: 'vip'
    biome: PLAINS
    access:
      type: DIAMOND
      name: '&6&lVIP island &2(Available)'
      lore:
        - '&7VIP Island'
    no-access:
      type: DIAMOND
      name: '&6&lVIP ostrov &4(Unavailable)'
      lore:
        - '&cYou need to buy VIP first!'
        - ''
        - '&7VIP Island'

sounds:
  'V':
    type: BLOCK_PORTAL_AMBIENT
    volume: 1
    pitch: 0.2

permissions:
  'V':
    permission: 'superior.schematic.vip'
    no-access-sound:
      type: BLOCK_ANVIL_PLACE
      volume: 0.2
      pitch: 0.2
```

You have 'items' and `permissions` apart, then you will add char you are defining in both of them.

Hope that helps!
