### ISSUE TITLE
Block Place Missions negative count and plugin reload mission reset

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1994]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15751 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3731381 on paper_upstream)

### Plugin's Version

2023.3-b136
+ ASWM (2.10.0)

### Describe the bug

There are two bugs, which are related:

1) When player has zero progress in `BlocksMissions` mission with option `blocks-placement` set to `true` and destroys the block, which he is supposed to place, his progress will go to negative numbers

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79375965/0be5ea2a-6742-4bbb-b1b1-55bf263db42c)

Important config parts:

```yml
mission-file: BlocksMissions
blocks-placement: true
required-blocks:
  '1':
    types:
      - 'SUGAR_CANE'
    amount: 8
  '2':
    types:
      - 'CACTUS'
    amount: 8
```

2) When you reload plugin with `/is admin reload`, all progress on NOT-COMPLETED missions is lost

### To Reproduce

1) Block Place Missions negative count
- Create a `BlocksMissions` mission with option `blocks-placement` set to `true`
- Set any block in `required-blocks` section and then destroy it in game
- Look how your progress goes into negative numbers

2) Plugin reload mission reset
- Do a progress on any mission and do not complete it
- Execute `/is admin reload` command
- Check on the mission progress
