### ISSUE TITLE
Section 'required-permission' in biomes.yml for menu not working.

### ISSUE THREAD

**Issue by Merunko** [BG-Software-LLC/SuperiorSkyblock2#2016]
### Minecraft's Version

Minecraft version: API 1.20.1-R0.1-SNAPSHOT, Paper-196

### Plugin's Version

Plugin version: `Stable build 2023.3` and `Dev build 2023.3-b147`

### Describe the bug

Access to biome change always accessible even when player do not have the permission.
Using LuckPerm as a permission provider. Permission check works in upgrades.yml but not in biomes.yml.

I cannot find if it's a problem from my side or the plugin so I just opened a thread here in case it is really plugin problem. Tested both Stable build and latest Dev build in localhost and problem still exist.

Console: `[16:52:59 INFO]: [SuperiorSkyblock2] Using LuckPerms as a permissions provider.`

### To Reproduce

Tried using section `required-permisson:` or `permission:` but both not working.
```
'!':
    biome: PLAINS
    required-permission: 'group.tofu'
    access:
      type: PLAYER_HEAD
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzk1ZDM3OTkzZTU5NDA4MjY3ODQ3MmJmOWQ4NjgyMzQxM2MyNTBkNDMzMmEyYzdkOGM1MmRlNDk3NmIzNjIifX19'
      name: '&ePlains Biome &a(Available)'
      lore:
        - '&7Change your island biome to plains.'
    no-access:
      type: PLAYER_HEAD
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzk1ZDM3OTkzZTU5NDA4MjY3ODQ3MmJmOWQ4NjgyMzQxM2MyNTBkNDMzMmEyYzdkOGM1MmRlNDk3NmIzNjIifX19'
      name: '&ePlains Biome &c(Unavailable)'
      lore:
        - '&7Change your island biome to plains.'
```
