### ISSUE TITLE
Entity Limit Bypassed After Server Restart

### ISSUE THREAD

**Issue by Merunko** [BG-Software-LLC/SuperiorSkyblock2#2044]
### Minecraft's Version

Paper version Paper-196 (MC: 1.20.1) API version 1.20.1-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2-2023.3-b155

### Describe the bug

I'm back after the RoseStacker issue. I missed something crucial. Umm but this one I believe someone reported it for entity limit Hopper or Minecart but this time it applies to probably all animals. I only tested it on Sheep.

### To Reproduce

In `config.yml`, set
```
entity-limits:
    MINECART: 4
    SHEEP: 3
```

In `modules/upgrades/config.yml`, set
```
upgrades:
  sheep-limit:
    '1':
      price: 1000000.0
      price-type: "money"
      entity-limits:
        SHEEP: 3
      commands: []
```

Next, place 3 Sheep on island.

Then, restart server.

And the old 3 sheep will not be counted and you can place new 3 Sheep. Thus, giving you 6 total of Sheeps.

### Additional Information

Clean server with only SuperiorSkyblock2-2023.3-b155 plugin. I found out this while using RoseStacker but turns out the issue lies within SuperiorSkyblock2 plugin and no interference from other plugin to cause this issue.
