### ISSUE TITLE
Island member and coop players can not pickup axolotl in their joined/trusted island

### ISSUE THREAD

**Issue by nhanledev** [BG-Software-LLC/SuperiorSkyblock2#2048]
### Minecraft's Version

Paper 1.20.4 build 455

### Plugin's Version

SuperiorSkyblock2-2023.3-b155

### Describe the bug

Island member and coop player can not pick axolotl up using water bucket. Only owner can.
They are trusted / invited to the island and can build, modify other stuff.

### To Reproduce

- Spawn axolotl
- Trust/Coop other user OR invite other user
- Use water bucket to pick the axolotl up
- The action is denied

What to expect: axolotl can be picked up

### Additional Information

```
island-roles:
  # This role is given to players that are not part of your island.
  guest:
    # A custom name for the role.
    name: Visitor
    # A list of default permissions for guests.
    permissions: []

  # This role is given to players that are co-op.
  coop:
    name: Trusted
    permissions:
    - ANIMAL_BREED
    - ANIMAL_DAMAGE
    - ANIMAL_SHEAR
    - BREAK
    - BUILD
    - CHEST_ACCESS
    - CLOSE_BYPASS
    - CROPS_GROWTH
    - DROP_ITEMS
    - ENDER_PEARL
    - EXPEL_BYPASS
    - FARM_TRAMPING
    - FERTILIZE
    - FISH
    - HORSE_INTERACT
    - INTERACT
    - ITEM_FRAME
    - LEASH
    - MINECART_DAMAGE
    - MINECART_ENTER
    - MINECART_OPEN
    - MINECART_PLACE
    - MONSTER_DAMAGE
    - NAME_ENTITY
    - PAINTING
    - PICKUP_DROPS
    - PICKUP_FISH
    - SIGN_INTERACT
    - TURTLE_EGG_TRAMPING
    - USE
    - VILLAGER_TRADING

  # The roles ladder for island members.
  # All the island member roles go here.
  #  - You can add as many roles as you'd like.
  #  - The default role for new members has a weight of 0.
  #  - Every role has all the permissions of the role before it.
  #  - Every role should have a custom id, to determine the role if the name is changed.
  #    Do not change ids!!! They don't have to be in an order.
  ladder:
    member:
      id: 0
      name: Member
      weight: 0
      permissions:
      - ANIMAL_SPAWN
      - CHEST_ACCESS
      - DEPOSIT_MONEY
      - ISLAND_CHEST
      - MONSTER_SPAWN
      - RANKUP
      - SPAWNER_BREAK
 ```
