### ISSUE TITLE
SafariNet

### ISSUE THREAD

**Issue by Bragos24** [BG-Software-LLC/SuperiorSkyblock2#2181]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

2024.1

### Describe the bug

Hi, I am using SafariNet plugin which allows you to catch Mobs and move them to another place.
Island Leader can capture and move mobs, but normal island members (or even admins) can't, only the owner can.
The only way to allow members to capture and move mobs is to enable the "all" permission in /is perms. I was wondering if there was another way, because enabling all permissions is very risky for players. Thanks in advance.

### To Reproduce

Try to catch or place a mob while you are a member of an island (but not the leader).

### Additional Information

SafariNet: https://www.spigotmc.org/resources/%E2%9C%85-safarinet-premium-mob-catcher-plugin.9732/

**Comment by leon37921** [comment]
You can add this to plugins/SuperiorSkyblock2/menus/permissons.yml
```
  safarinet:
    display-menu: true
    permission-enabled:
      type: GHAST_SPAWN_EGG
      name: '&6SafariNetze'
      lore:
        - '&7Erlaubt das Fangen und Freilassen von Tieren auf deiner Insel.'
        - '&7Status: &aAktiviert&7.'
    permission-disabled:
      name: '&6SafariNetze'
      type: GHAST_SPAWN_EGG
      lore:
        - '&7Erlaubt das Fangen und Freilassen von Tieren auf deiner Insel.'
        - '&7Status: &cDeaktiviert&7.'
    role-permission:
      name: '&6SafariNetze'
      type: GHAST_SPAWN_EGG
      lore:
        - '&7Erlaubt das Fangen und Freilassen von Tieren auf deiner Insel.'
        - '&7Gruppe: &e{}&7.'
        - ''
        - '{0}'
    has-access:
      sound:
        type: ENTITY_EXPERIENCE_ORB_PICKUP
        volume: 0.2
        pitch: 0.2
    no-access:
      sound:
        type: BLOCK_ANVIL_PLACE
        volume: 0.2
        pitch: 0.2
        
```
this should work 
(translate lore into your language)
