### ISSUE TITLE
Island visitors do not pickup all experience orbs

### ISSUE THREAD

**Issue by MMN-2024** [BG-Software-LLC/SuperiorSkyblock2#2294]
### Minecraft's Version

Paper version 1.21.1-132-ver/1.21.1@b48403b

### Plugin's Version

SuperiorSkyblock2 version 2024.4

### Describe the bug

Island visitors (guests) do not pickup all experience orbs on the floor. 

### To Reproduce

Use the default configuration of superiorskyblock. Ensure the guest role has `PICKUP_DROPS', 'DROP_ITEMS' and 'MONSTER_DAMAGE' permissions.

Visit an island of another player.
Kill some mobs/monsters.
You will notice that you'll obtain some experience, but that some orbs will keep floating around you.

Enable /is admin bypass, you will notice that you'll get the experience orbs added which were laying on the floor.

### Additional Information

https://youtu.be/DlCp-1ppIA0

**Comment by OmerBenGera** [comment]
Are you able to replicate it on a server with only SSB installed? It seems to work fine for me
Sometimes I need to move around to pickup the exp orbs, but nothing other than that

**Comment by MMN-2024** [comment]
I am able to replicate it on a server with only SSB installed, see the youtube video for proof.

Default paper configuration files, default spigot.yml, default bukkit.yml, default SuperiorSkyblock configuration files, except that 
```
  guest:
    # A custom name for the role.
    name: 'Guest'
    # A list of default permissions for guests.
    permissions:
      - PICKUP_DROPS
      - MONSTER_DAMAGE
      - DROP_ITEMS
```
Everything else is default.
