### ISSUE TITLE
Island Mission not giving every connected members the reward

### ISSUE THREAD

**Issue by Gayytis** [BG-Software-LLC/SuperiorSkyblock2#2356]
### Minecraft's Version

Paper 1.21.4-138

### Plugin's Version

SuperiorSkyblock : 2024.4-b419

### Describe the bug

I used a mission already created to test island missions. However, it seems like Island Missions do not give every island member their reward when they are connected, only the one who finished the quest.

```yml
mission-file: BlocksMissions

# Whether the mission should be given when completing all requirements.
auto-reward: true
island: true

# Should block counts of players get reset when completing the mission?
#reset-after-finish: false

# Whether only naturally spawned blocks should be counted towards the mission or not.
only-natural-blocks: true
```

### To Reproduce

Here is a video showing what happens

https://github.com/user-attachments/assets/a5d6143f-3ffc-4aa9-bf2a-d747e639f832

### Additional Information

This is my configuration
![Image](https://github.com/user-attachments/assets/e812b31c-a718-4a68-9b7f-cf9bf02c3b3d)
